### ISSUE TITLE
World-gen crash

### ISSUE THREAD

**Issue by InteJason** [FatherToast/SpecialAI#10]
This crash happens during world-gen for both single player and server, but only servers give logs

https://paste.ee/p/Yct9B

From the above crash it mentions another mod, so I removed that mod to see if the issue is fixed, but it only leads to another mod being mentioned.

https://paste.ee/p/QsrDb

That made me think it's the problem with this mod, the version is the latest version for 1.16.5.

**Comment by FatherToast** [comment]
The logs appear to have expired, though the most recent version since this post may have fixed this issue.  If it still happens with the latest version, please post a new issue here.
