### ISSUE TITLE
Weird crash

### ISSUE THREAD

**Issue by mxnmnm** [FatherToast/SpecialAI#11]
It happened in an onslaught invasion, I was killing penghouls from fish's undead rising (they were part of the raid) and I crashed
https://gist.github.com/mxnmnm/4ff1d7096bcb902d290fee619ae132c7

**Comment by mxnmnm** [comment]
This is for 1.12 so I hope it still has support

**Comment by FatherToast** [comment]
Unfortunately as this is before 1.16.5, I can't do much on it.  I think the best best here is to disable elite AIs on the type of mob that crashed with it.  That said, these kinds of crashes should not cause any damage to the world, so if this crash is rare enough, you could just leave it as-is.
