### ISSUE TITLE
CQR Incompatibility? [1.12]

### ISSUE THREAD

**Issue by thedeerirty** [FatherToast/SpecialAI#12]
[latest.log](https://github.com/FatherToast/SpecialAI/files/7088319/latest.log)
Also reporting this to them as well, but it seems to delete the entities from said mod and the reason stated seemed related to their tasks? Any info on this you could give me? I love both mods, and if I can fix this in config to keep both I'd love to know

**Comment by DerToaster98** [comment]
the weird thing is that some thing removes methods from the BlockPos class, which results in some of our tasks generating a crash.
What you should do is 
0) Update CQR to 2.5.3B, you use 2.5.2B
1) Downgrade forge to 2847, cause that definitely works
2) If it still crashes, remove this mod and try to reproduce the issue. The crash should trigger when a cqr mob tries to path through a door (test this with a skeleton or pirate, cause those definitely have that ai task)
3) If it still crashes create a new issue on our tracker and provide us your configs

**Comment by FatherToast** [comment]
This does not appear to be an issue with Special AI; if you are still having the issue after following DerToaster's steps above, please post an issue on their tracker so they have better visibility (though I suspect this is just a versioning issue).
