### ISSUE TITLE
crash when installed with EpicFightMod

### ISSUE THREAD

**Issue by YivanLiu** [FatherToast/SpecialAI#13]
-- Entity being ticked --
Details:
	Entity Type: minecraft:zombie (net.minecraft.entity.monster.ZombieEntity)
	Entity ID: 949
	Entity Name: 僵尸
	Entity's Exact location: 66.90, 77.00, 355.10
	Entity's Block location: World: (66,77,355), Chunk: (at 2,4,3 in 4,22; contains blocks 64,0,352 to 79,255,367), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0.06, -0.08, 0.06
	Entity's Passengers: []
	Entity's Vehicle: SpiderEntity['蜘蛛'/950, l='ServerLevel[新的世界]', x=66.03, y=76.00, z=355.96]
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:biomancy.mixins.json:ServerWorldAccessor,pl:mixin:A}

According to the crash-report, it seemed to be a zombie or skeleton trying to ridding a spider causing this.

**Comment by WadjetSama** [comment]
it's 1.16.5

**Comment by Sarinsa** [comment]
Could you provide the entire log?

**Comment by Sarinsa** [comment]
Preferably use something like https://pastebin.com/

**Comment by DeMooniC** [comment]
Hello! I have the same problem also in ver 1.16.5, it seems to crash every time a skeleton or a zombie tries to ride a spider or a spider jokey spawns.
 I tested it and it is 100% that and all the crash logs say the same thing. IDK if it happens or not when they try to ride something else, I didn't test that yet but I don't think that's the case.
 
 **Here are the crash logs (first skeleton, second zombie):**
 https://pastebin.com/SiwLLjvy
 https://pastebin.com/aA3FRkey

**Comment by FatherToast** [comment]
Thank you, this is very helpful information for tracking down exactly what causes it!  Hopefully this helps us get there.

**Comment by DeMooniC** [comment]
You are welcome! Thank you for the amazing mod :D

I really don't want to remove it from my modpack, adds some nice difficulty and depth into the game

**Comment by Sarinsa** [comment]
Should be fixed in most recent release
