### ISSUE TITLE
Incompatible with epic fight, check linked issue 

### ISSUE THREAD

**Issue by notkidgamer23** [FatherToast/SpecialAI#16]
Talked with yesman and figured out specialAI is incompatible with epic fight causing crashing. Yesman said if you know what the cause is he'll modify his code, you can check the logs and what he said here https://github.com/Yesssssman/epicfightmod/issues/638

**Comment by notkidgamer23** [comment]
Epic fight version 5.1.3
Special AI version 1.0.1

**Comment by Sarinsa** [comment]
Should be fixed in most recent release
