### ISSUE TITLE
Entities are invisible with this mod

### ISSUE THREAD

**Issue by MinecraftPerson** [FatherToast/SpecialAI#23]
**Setup**
- Dedicated server? Yes/No
- Special AI version:  1.16.5
- Forge version: 
- Other involved mod version (if applicable): 

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Reports**
If applicable, add links to crash reports (for crashes), game logs (for freezes), and/or configs.

**Comment by Sarinsa** [comment]
Yo! Are you able to provide more details? Such as Forge version and other installed mods that may cause the problem? Special AI by itself does not do this, so I believe there must be another mod causing the bug either by itself or in combination with Special AI
