### ISSUE TITLE
Incompatability Issue with 'Berry Cows' Mod

### ISSUE THREAD

**Issue by AnimePixie** [FatherToast/SpecialAI#24]
**Setup**
- Dedicated server? seems to be an issue with both yes and no
- Special AI version:  1.0.2
- Forge version: 36.2.34
- Other involved mod version (if applicable): Berry Cows v1.0.3

**Describe the bug**
Hi, I'm A beginner modder that's been developing a mod called 'Berry Cows', recent two users reported to me that when used with Special AI the textures on my Cows break. I was wondering If it would be possible to get some help working out what the code is I need to adjust? 

from what i see looking at a log I have it looks like it has something to do with the species selection, in my mod there are 33 different species of berry cow and there are systems in the code that dictate how each entity selects it species. Judging from the logs it looks like my code is correctly selecting the species then something is causing the ID number that dictates this to be subtracted from constantly  resulting in the code updating the texture to be the ID 0 and then negative numbers, which obviously do not exist.  I hope that helps a bit ^_^;

**To Reproduce**
install both 'special AI' and 'Berry Cows' on the same instance of Minecraft. 

**Reports**
I don't a github report set up but you can see the reports in the comment here: https://www.curseforge.com/minecraft/mc-mods/berry-cows
[
Link to Log mentioned
](https://www.dropbox.com/s/ydizdl03l2dz5fs/latest.log?dl=0)

**Comment by Sarinsa** [comment]
Are you able to provide a link of sorts to your code? A bit tricky without a repository, but that would help us a lot on getting a clue as to what could be causing it!

**Comment by AnimePixie** [comment]
Hi, sure I have Zipped the MCreator Workspace here:
https://www.dropbox.com/s/6hn8xx4m3pbwf0l/berrycows.zip?dl=0
I hope that helps

**Comment by Sarinsa** [comment]
Ah oof, if its an mcreator project that complicates things a bit. Ill see if I can figure something out, but my knowledge with mcreator is nonexistent

**Comment by FatherToast** [comment]
This is a lot of code to look through without an IDE or something.  Where all do you modify the cow variant in your code?  Does the glitch still happen with the AIs "eat breeding items" and/or "depacify" disabled?

**Comment by AnimePixie** [comment]
you'll want to look in "BerryCowsSpawnTexture", "OnBreedingEvent" and 'Checkforhybrid" i think. If 'eat breeding items' is disabled in the config the issue doesn't occur, so i guess it has something to do with that.

**Comment by FatherToast** [comment]
Okay, the problem appears to be in "BerryCowEatGrassProcedure".  It looks like it ends up decrementing the variant every time "EntityMobGriefingEvent" is fired; this event is used to check if a mob is allowed to grief, so you should not perform any actions in response to it.

**Comment by AnimePixie** [comment]
ah I see, ty, any advice on what i should be using instead? I basically just needed something to 'grow back' the berry's after it eats grass.
