### ISSUE TITLE
[Crash] Incompatibility with Roadrunner Entity Tracking mixins when an entity tracking the player decides to mount something

### ISSUE THREAD

**Issue by Kaleidio** [FatherToast/SpecialAI#25]
https://github.com/Insane96/EnhancedAI/issues/75

**Comment by Kaleidio** [comment]
```java.lang.IllegalStateException: Adding Entity listener a second time: me.jellysquid.mods.lithium.common.entity.tracker.nearby.NearbyEntityListenerMulti@7eb1791c with sublisteners: [me.jellysquid.mods.lithium.common.entity.tracker.nearby.NearbyEntityTracker@6befe50c for entity class: ```

this fails because it's trying to force the zombie's mount to move as your mod provides mixins that allow mounted entities to control the direction their mount moves.  roadrunner does not allow you to process two player search actions at once for the same tracker entity.  **in this case, your zombie is attempting to register a "track player" on behalf of its mounted entity even though it is also trying to track the player itself simultaneously** (which is in this case a boat, even tho that would gracefully fail anyway as the zombie cannot drive the boat)

every entity tracking event must be registered a single time per tick by different entities.  for example, two zombies can register tracking events, but one zombie should not track two things at once (event systems are not designed to handle that.)

note this is mostly because roadrunner has turned this part of the ai into an event based system.   this was done because it was assumed safe because no entity code even registers more than one tracking goal at a given time.  however, yours can if the entity is mounted

**Comment by FatherToast** [comment]
This should be directed toward Roadrunner.  If there is some reasonable change I can make to help SAI play along nicely, then I can do that, but I have no idea how their system works to be able to make that change.

Some additional info that may help:  SAI only calls vanilla pathfinding methods, does not use any mixins, and does not modify rider/mount behavior.  For most entities (including zombies), it exclusively adds regular non-target tasks.

**Comment by Kaleidio** [comment]
strange, the issue only happens when entities are mounted whilst your mod is installed.  I guess something else is going on.  I'll just let roadrunner be because mod development has been abandoned.

**Comment by FatherToast** [comment]
Hm, it is a shame to hear that, as I would be clueless as to where to even look for something in SAI that leads to the crash, since SAI is not referenced in the stack trace.
The call for help thing is really a vanilla task, which is already on some mobs, including zombies.
