### ISSUE TITLE
Some entities are "vacuuming" when they shouldn't.

### ISSUE THREAD

**Issue by Kaleidio** [FatherToast/SpecialAI#28]
**Setup**
- Dedicated server? Irrelevant
- Special AI version: 1.1.0
- Forge version: 36.2.39
- Other involved mod version (if applicable): ItemPhysic 1.4.18

**Describe the bug**
The player, for example, is being counted as a "passive" mob, which causes the player to try vacuuming items.  If ItemPhysic is installed and Custom Pickup is enabled in its config, this results in the item getting stuck in the player's head.

**To Reproduce**
Install both mods.
Run the game once to generate configs.
Find the key in itemphysic.json called "customPickup", and set it to true.  Alternatively, use the config file uploaded here.
Relaunch the game and play in a world
Kill a chicken (as a super duper simple example)
Watch as its meat and feather get stuck in the player's face via vacuuming.

**Reports**
[itemphysic.json](https://github.com/user-attachments/files/15891129/itemphysic.json)

**Comment by Sarinsa** [comment]
Are you referring to the "magnet mode"? If so, that is part of Crust, not Special AI. If you could, please copy this issue and open a new one in Crust's issue tracker

**Comment by Sarinsa** [comment]
You can look at crust as a foundation that will eventually act as a base mod for the other mods. It is both a library and a collection of features that are used between many of the mods
