### ISSUE TITLE
New world gen stuck

### ISSUE THREAD

**Issue by Revelates** [FatherToast/SpecialAI#7]
No crash logs or anything sadly, just gets stuck at 100% when making a new world, works completely fine without the mod in my pack, or when I select an already created world to play on.

**Comment by FatherToast** [comment]
I have narrowed this down to where it happens from my side, but no idea why it happens.  Will attempt a fix in the next version, but I can't guarantee it will work.

**Comment by FatherToast** [comment]
Version 1.0.1 is out and hopefully fixes the issue.  I could not reproduce the deadlock reliably, but I haven't been able to get it with the updated version.  If it works for you after updating, let me know and I will close the issue.

**Comment by Revelates** [comment]
Will do

**Comment by Revelates** [comment]
Yeah works fine now, Thanks for fixing it!

**Comment by Jackiecrazy** [comment]
[Entity.kill()](https://github.com/FatherToast/SpecialAI/blob/a6cb4efa7da5dbb59009b41f6e348f3ce9fa723b/src/main/java/fathertoast/specialai/config/util/EntityEntry.java#L58) will call LivingDeathEvent on forge, which will cause deadlocks if a mod attempts to perform some action that requires accessing the world. There is a function that bypasses the kill and directly removes the mob, though the name currently eludes me.
